import React from 'react';
import { Property, UnitType, CurrencyType, ConsultationInquiry } from '../types';
import { PropertyCard } from '../components/PropertyCard';
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';
import { LocationsSection } from '../components/LocationsSection';
import { ServicesSection } from '../components/ServicesSection';
import { formatManwonToUSD, formatArea } from '../utils/formatters';

const shell = (children: React.ReactNode, props: any) => <div className="min-h-screen bg-white text-[#171717]"><Navbar {...props} /><main className="pt-[106px]">{children}</main><Footer onOpenCalculator={props.onOpenCalculator || (() => {})} onOpenSellModal={props.onOpenSellModal} onOpenAdminModal={props.onOpenAdminModal || (() => {})} /></div>;
const SectionTitle = ({eyebrow,title,ko}:{eyebrow:string;title:string;ko?:string}) => <div className="border-b border-black/10 pb-7"><p className="text-[9px] tracking-[0.25em] text-black/45">{eyebrow}</p><h1 className="mt-3 text-4xl font-light tracking-[-0.025em] sm:text-5xl">{title}</h1>{ko && <p className="mt-2 text-sm text-black/45">{ko}</p>}</div>;

export function ListingsPage({properties,...props}:{properties:Property[];[key:string]:any}) { return shell(<section className="mx-auto max-w-[1440px] px-6 py-16 lg:px-10 lg:py-24"><SectionTitle eyebrow="LISTINGS · 매물" title="Homes for sale & rent" ko="뉴저지 매매 · 렌트 매물"/><div className="mt-8 grid grid-cols-1 gap-x-8 gap-y-14 md:grid-cols-2 lg:grid-cols-3">{properties.map(p=><PropertyCard key={p.id} property={p} isFavorite={false} onToggleFavorite={()=>{}} onSelectProperty={(x)=>window.location.href=`/property/${x.id}`} unit="sqft" currency="USD" />)}</div></section>,props); }

export function BuyPage({properties,...props}:{properties:Property[];[key:string]:any}) { const homes=properties.filter(p=>p.listingType==='sale'); return shell(<><section className="bg-[#f5f5f2] px-6 py-16 lg:px-10 lg:py-24"><div className="mx-auto max-w-[1200px]"><SectionTitle eyebrow="BUY · 구매" title="Find your next home" ko="뉴저지에서 살 집을 찾아보세요."/><div className="mt-10 grid gap-8 md:grid-cols-3"><Info n="01" t="Search" k="원하는 지역과 예산을 정합니다."/><Info n="02" t="Tour" k="집을 직접 보고 비교합니다."/><Info n="03" t="Offer & Close" k="오퍼부터 클로징까지 함께합니다."/></div></div></section><ListingStrip title="Featured homes" ko="추천 매물" properties={homes.slice(0,6)} /></>,props); }

export function RentPage({properties,...props}:{properties:Property[];[key:string]:any}) { const homes=properties.filter(p=>p.listingType==='rent'); return shell(<><section className="bg-[#f5f5f2] px-6 py-16 lg:px-10 lg:py-24"><div className="mx-auto max-w-[1200px]"><SectionTitle eyebrow="RENT · 렌트" title="Rent in North Jersey" ko="뉴저지 렌트 매물을 찾아보세요."/><div className="mt-10 grid gap-8 md:grid-cols-3"><Info n="01" t="Choose a town" k="지역과 통근 환경을 확인합니다."/><Info n="02" t="Apply" k="필요 서류와 조건을 안내합니다."/><Info n="03" t="Move in" k="리스 계약부터 입주까지 도와드립니다."/></div></div></section><ListingStrip title="Current rentals" ko="현재 렌트 매물" properties={homes} /></>,props); }

export function SellPage(props:any) { return shell(<><section className="mx-auto max-w-[1200px] px-6 py-16 lg:px-10 lg:py-24"><SectionTitle eyebrow="SELL · 매도" title="Sell with local market knowledge" ko="뉴저지 현지 시장을 기준으로 매도 전략을 세웁니다."/><div className="mt-12 grid gap-12 lg:grid-cols-2"><div><h2 className="text-2xl font-light">From pricing to closing.</h2><p className="mt-5 text-sm leading-7 text-black/55">Market analysis, listing preparation, photography, online marketing, showing coordination, offer review and negotiation are handled as one process.</p><p className="mt-4 text-sm leading-7 text-black/55">가격 분석부터 MLS 리스팅, 마케팅, 쇼잉, 오퍼 협상, 클로징까지 한국어와 영어로 안내합니다.</p></div><div className="border-t border-black/10 pt-6"><Info n="01" t="Market analysis" k="Comparable sales와 지역 수요를 분석합니다."/><Info n="02" t="Listing & marketing" k="MLS와 주요 부동산 채널에 노출합니다."/><Info n="03" t="Negotiation & closing" k="오퍼부터 클로징까지 진행합니다."/></div></div><a href="/contact" className="mt-12 inline-block border-b border-black pb-2 text-[10px] tracking-[0.16em]">REQUEST A HOME VALUATION · 매도 상담</a></section></>,props); }

export function CommunitiesPage({properties,...props}:{properties:Property[];[key:string]:any}) { const areas=[['Fort Lee','Bergen County','NYC access, shopping and river views'],['Palisades Park','Bergen County','Korean-American community and convenient transit'],['Edgewater','Hudson County','Waterfront living and Manhattan views'],['Tenafly','Bergen County','Residential streets and strong school district'],['Closter','Bergen County','Larger lots, parks and suburban living']]; return shell(<><section className="mx-auto max-w-[1200px] px-6 py-16 lg:px-10 lg:py-24"><SectionTitle eyebrow="COMMUNITIES · 지역" title="Explore North Jersey" ko="뉴저지 주요 지역을 알아보세요."/><div className="mt-12 divide-y divide-black/10">{areas.map(([name,county,copy],i)=><a key={name} href={`/listings?area=${encodeURIComponent(name)}`} className="grid grid-cols-[60px_1fr_auto] items-center gap-5 py-7 hover:bg-[#f7f7f4] sm:grid-cols-[80px_1fr_1fr_auto]"><span className="text-[10px] text-black/35">0{i+1}</span><div><h2 className="text-xl font-medium">{name}</h2><p className="mt-1 text-xs text-black/40">{county}</p></div><p className="hidden text-sm text-black/50 sm:block">{copy}</p><span className="text-lg">→</span></a>)}</div></section><LocationsSection onSelectDistrictFilter={(d)=>window.location.href=`/listings?area=${encodeURIComponent(d)}`} /></>,props); }

export function AboutPage(props:any) { return shell(<section className="mx-auto max-w-[1200px] px-6 py-16 lg:px-10 lg:py-24"><SectionTitle eyebrow="ABOUT · 소개" title="A local real estate partner in New Jersey" ko="뉴저지 현지 시장을 아는 한국어 · English 부동산 서비스"/><div className="mt-12 grid gap-12 lg:grid-cols-2"><img className="aspect-[4/3] w-full object-cover" src="https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1800&q=85" alt="New Jersey home"/><div><p className="text-lg leading-8">We help buyers, sellers, renters and relocating families navigate North Jersey real estate with clear local guidance.</p><p className="mt-6 text-sm leading-7 text-black/55">Bergen County와 Hudson County를 중심으로 지역 선택, 매물 검색, 오퍼, 협상, 렌트, 클로징까지 실무적인 도움을 제공합니다.</p><div className="mt-10 grid grid-cols-2 border-t border-black/10 pt-5 text-xs"><div><span className="text-black/40">LANGUAGES</span><p className="mt-2">English · 한국어</p></div><div><span className="text-black/40">SERVICE AREA</span><p className="mt-2">North Jersey · NYC Metro</p></div></div></div></div></section>,props); }

export function ContactPage(props:any) { return shell(<section className="mx-auto max-w-[1200px] px-6 py-16 lg:px-10 lg:py-24"><SectionTitle eyebrow="CONTACT · 상담" title="Let's talk real estate" ko="구매 · 매도 · 렌트 상담"/><div className="mt-12 grid gap-12 lg:grid-cols-2"><div><p className="text-2xl font-light">(201) 555-0188</p><p className="mt-2 text-sm text-black/45">hello@theaddressnj.com</p><p className="mt-8 text-sm leading-7 text-black/55">Tell us what you are looking for, where you want to live, and your target price range. We will follow up in English or Korean.</p></div><form onSubmit={(e)=>{e.preventDefault(); props.onSubmitInquiry?.({name:(e.currentTarget.elements.namedItem('name') as HTMLInputElement).value,phone:(e.currentTarget.elements.namedItem('phone') as HTMLInputElement).value,type:'consultation',email:(e.currentTarget.elements.namedItem('email') as HTMLInputElement).value,targetRegion:(e.currentTarget.elements.namedItem('region') as HTMLInputElement).value});}} className="space-y-4"><input name="name" required placeholder="Name / 이름" className="w-full border-b border-black/20 px-0 py-4 text-sm outline-none"/><input name="phone" required placeholder="Phone / 전화번호" className="w-full border-b border-black/20 px-0 py-4 text-sm outline-none"/><input name="email" placeholder="Email" className="w-full border-b border-black/20 px-0 py-4 text-sm outline-none"/><input name="region" placeholder="Preferred area / 희망 지역" className="w-full border-b border-black/20 px-0 py-4 text-sm outline-none"/><button className="mt-4 bg-[#171717] px-7 py-4 text-[10px] tracking-[0.16em] text-white">SUBMIT · 상담 신청</button></form></div></section>,props); }

export function PropertyDetailPage({property,...props}:{property:Property;[key:string]:any}) { const [saved,setSaved]=React.useState(false); return shell(<article><div className="mx-auto max-w-[1440px]"><div className="grid grid-cols-2 gap-1 bg-black lg:grid-cols-4">{property.images.map((img,i)=><img key={i} src={img} alt="" className={`h-[30vh] w-full object-cover lg:h-[42vh] ${i>1?'hidden lg:block':''}`} />)}</div><div className="mx-auto max-w-[1200px] px-6 py-12 lg:px-10 lg:py-16"><div className="flex flex-col gap-8 border-b border-black/10 pb-10 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[9px] tracking-[0.2em] text-black/45">{property.listingType==='sale'?'FOR SALE':'FOR RENT'} · {property.district}</p><h1 className="mt-3 text-3xl font-light sm:text-5xl">{property.titleKo}</h1><p className="mt-3 text-sm text-black/50">{property.roadAddress}</p></div><div className="lg:text-right"><p className="text-3xl font-medium">{formatManwonToUSD(property.price)}{property.listingType==='rent'&&<span className="text-base font-normal text-black/45"> / month</span>}</p><button onClick={()=>setSaved(!saved)} className="mt-4 border-b border-black pb-1 text-[10px] tracking-[0.14em]">{saved?'SAVED · 관심매물':'SAVE PROPERTY · 관심매물'}</button></div></div><div className="grid grid-cols-2 gap-y-8 border-b border-black/10 py-10 sm:grid-cols-4"><Stat t="BEDS" v={`${property.rooms}`} /><Stat t="BATHS" v={`${property.baths}`} /><Stat t="LIVING AREA" v={formatArea(property.exclusivePyeong,property.exclusiveAreaM2,'sqft')} /><Stat t="PARKING" v={`${property.parking} Cars`} /><Stat t="YEAR BUILT" v={`${property.builtYear}`} /><Stat t="PROPERTY TYPE" v={property.propertyType==='house'?'Single Family':property.propertyType==='apartment'?'Condo / Apartment':'Property'} /><Stat t="DISTRICT" v={property.district} /><Stat t="MLS STATUS" v={property.listingType==='sale'?'Active':'For Rent'} /></div><div className="grid gap-14 py-12 lg:grid-cols-[1.6fr_1fr]"><div><h2 className="text-xl font-medium">Property overview</h2><p className="mt-5 text-sm leading-7 text-black/60">{property.descriptionKo}</p><h2 className="mt-12 text-xl font-medium">Features & amenities</h2><div className="mt-5 grid grid-cols-2 gap-y-3 text-sm text-black/55">{property.features.map(f=><p key={f}>— {f}</p>)}</div></div><aside className="border-t border-black/10 pt-6"><p className="text-[9px] tracking-[0.2em] text-black/40">LISTING AGENT</p><div className="mt-4 flex items-center gap-4"><img src={property.agent.avatar} className="h-14 w-14 rounded-full object-cover"/><div><p className="font-medium">{property.agent.name}</p><p className="text-xs text-black/45">{property.agent.title}</p></div></div><p className="mt-5 text-sm">{property.agent.phone}</p><a href="/contact" className="mt-5 block bg-[#171717] px-6 py-4 text-center text-[10px] tracking-[0.15em] text-white">REQUEST A TOUR · 투어 상담</a></aside></div></div></div></article>,props); }

function ListingStrip({title,ko,properties}:{title:string;ko:string;properties:Property[]}) { return <section className="mx-auto max-w-[1440px] px-6 py-16 lg:px-10 lg:py-20"><div className="flex items-end justify-between border-b border-black/10 pb-6"><div><p className="text-[9px] tracking-[0.22em] text-black/40">{title.toUpperCase()}</p><h2 className="mt-2 text-3xl font-light">{ko}</h2></div><a href="/listings" className="text-[10px] tracking-[0.15em]">VIEW ALL →</a></div><div className="mt-10 grid gap-10 md:grid-cols-2 lg:grid-cols-3">{properties.map(p=><PropertyCard key={p.id} property={p} isFavorite={false} onToggleFavorite={()=>{}} onSelectProperty={(x)=>window.location.href=`/property/${x.id}`} unit="sqft" currency="USD" />)}</div></section>; }
function Info({n,t,k}:{n:string;t:string;k:string}) { return <div className="border-t border-black/10 pt-5"><span className="text-[10px] text-black/35">{n}</span><h3 className="mt-5 text-lg font-medium">{t}</h3><p className="mt-2 text-sm leading-6 text-black/50">{k}</p></div>; }
function Stat({t,v}:{t:string;v:string}) { return <div><p className="text-[9px] tracking-[0.16em] text-black/40">{t}</p><p className="mt-2 text-sm">{v}</p></div>; }
