import React, { useState } from 'react';
import { FilterState, ListingType } from '../types';
interface HeroSearchProps { filters: FilterState; setFilters: React.Dispatch<React.SetStateAction<FilterState>>; totalCount?: number; onOpenCalculator?: () => void; onOpenSellModal?: () => void; }
export const HeroSearch: React.FC<HeroSearchProps> = ({ filters, setFilters, onOpenSellModal }) => {
 const [activeTab,setActiveTab]=useState<'sale'|'rent'|'sell'>('sale'); const [query,setQuery]=useState(filters.searchQuery);
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(activeTab==='sell'){onOpenSellModal?.();return;}setFilters(p=>({...p,listingType:activeTab as ListingType,searchQuery:query}));document.getElementById('properties-section')?.scrollIntoView({behavior:'smooth'});};
 const quick=(district:string)=>{setFilters(p=>({...p,district,searchQuery:''}));document.getElementById('properties-section')?.scrollIntoView({behavior:'smooth'});};
 return <section className="relative flex min-h-[650px] items-end overflow-hidden bg-[#292929] text-white lg:min-h-[720px]"><div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=2400&q=88" alt="New Jersey home" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-black/35"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/15 to-black/10"/></div><div className="relative z-10 mx-auto w-full max-w-[1440px] px-6 pb-12 lg:px-10 lg:pb-16"><p className="text-[10px] tracking-[.24em] text-white/65">NORTH JERSEY · NEW JERSEY</p><h1 className="mt-4 max-w-3xl text-5xl font-light leading-[1.03] tracking-[-.035em] sm:text-6xl lg:text-[76px]">Find your place in<br/>New Jersey.</h1><div className="mt-10 max-w-[980px]"><div className="flex gap-8 border-b border-white/35 text-[11px] font-medium tracking-[.16em]"><button onClick={()=>setActiveTab('sale')} className={`pb-3 ${activeTab==='sale'?'border-b border-white text-white':'text-white/55'}`}>BUY</button><button onClick={()=>setActiveTab('rent')} className={`pb-3 ${activeTab==='rent'?'border-b border-white text-white':'text-white/55'}`}>RENT</button><button onClick={()=>setActiveTab('sell')} className={`pb-3 ${activeTab==='sell'?'border-b border-white text-white':'text-white/55'}`}>SELL</button></div><form onSubmit={submit} className="mt-0 flex max-w-[900px] flex-col bg-white text-[#171717] shadow-xl sm:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="City, neighborhood, address or ZIP code" className="min-h-[64px] flex-1 px-6 text-[14px] outline-none placeholder:text-black/35"/><button className="min-h-[64px] bg-[#171717] px-10 text-[10px] font-semibold tracking-[.18em] text-white">SEARCH</button></form><div className="mt-5 flex flex-wrap gap-5 text-[11px] text-white/70"><span className="text-white/40">EXPLORE</span>{['Fort Lee','Palisades Park','Edgewater','Tenafly','Closter'].map(x=><button key={x} onClick={()=>quick(x)} className="hover:text-white">{x}</button>)}</div></div></div></section>;
};
