import { ListingType } from '../types';

export function formatManwonToKorean(manwon: number): string { if (!manwon || manwon <= 0) return '0원'; const eok = Math.floor(manwon / 10000); const remainder = manwon % 10000; if (eok > 0 && remainder > 0) return `${eok.toLocaleString()}억 ${remainder.toLocaleString()}만원`; if (eok > 0) return `${eok.toLocaleString()}억원`; return `${remainder.toLocaleString()}만원`; }
export function formatPropertyPrice(listingType: ListingType, priceInManwon: number, deposit?: number, monthlyRent?: number): string { if (listingType === 'jeonse') return `전세 ${formatManwonToKorean(deposit || priceInManwon)}`; if (listingType === 'rent') return `보증금 ${formatManwonToKorean(deposit || 10000)} / 월 ${monthlyRent || 300}만원`; return `매매 ${formatManwonToKorean(priceInManwon)}`; }
export function formatManwonToUSD(manwon: number): string { const krw = manwon * 10000; const usd = Math.round(krw / 1380); return `$${usd.toLocaleString()}`; }
export function formatArea(pyeong: number, m2: number, unit: 'pyeong' | 'm2' | 'sqft'): string { if (unit === 'sqft') return `${Math.round(m2 * 10.7639).toLocaleString()} sqft`; if (unit === 'pyeong') return `${pyeong}평`; return `${m2}㎡`; }

export function calculateAcquisitionTax(priceInManwon: number, houseCount: 1 | 2 | 3 = 1) { let baseRate = 0.03; if (houseCount === 1) { if (priceInManwon <= 60000) baseRate = 0.01; else if (priceInManwon <= 90000) baseRate = ((priceInManwon / 10000 * (2 / 3) - 3) * 0.01); } else if (houseCount === 2) baseRate = 0.08; else baseRate = 0.12; const acquisitionTax = Math.round(priceInManwon * baseRate); const localEduTax = Math.round(priceInManwon * (baseRate * 0.1)); const ruralSpecialTax = priceInManwon > 8500 ? Math.round(priceInManwon * 0.002) : 0; const totalTax = acquisitionTax + localEduTax + ruralSpecialTax; return { taxRate: Number(((totalTax / priceInManwon) * 100).toFixed(2)), totalTax, acquisitionTax, localEduTax, ruralSpecialTax }; }
export function calculateBrokerageFee(priceInManwon: number, listingType: ListingType) { let rate = 0.007; if (listingType === 'sale' || listingType === 'commercial') { if (priceInManwon < 5000) rate = 0.006; else if (priceInManwon < 20000) rate = 0.005; else if (priceInManwon < 90000) rate = 0.004; else if (priceInManwon < 120000) rate = 0.005; else if (priceInManwon < 150000) rate = 0.006; } else { if (priceInManwon < 5000) rate = 0.005; else if (priceInManwon < 10000) rate = 0.004; else if (priceInManwon < 90000) rate = 0.003; else if (priceInManwon < 120000) rate = 0.004; else if (priceInManwon < 150000) rate = 0.005; else rate = 0.006; } const maxFee = Math.round(priceInManwon * rate); const vat = Math.round(maxFee * 0.1); return { feeRate: Number((rate * 100).toFixed(2)), maxFee, vat, total: maxFee + vat }; }
export function calculateMortgageMonthly(principalManwon: number, annualInterestRate: number, years: number) { if (!principalManwon || principalManwon <= 0) return { monthlyPayment: 0, totalInterest: 0, totalPayment: 0 }; const monthlyRate = (annualInterestRate / 100) / 12; const totalMonths = years * 12; if (monthlyRate === 0) { const monthly = Math.round(principalManwon / totalMonths); return { monthlyPayment: monthly, totalInterest: 0, totalPayment: principalManwon }; } const x = Math.pow(1 + monthlyRate, totalMonths); const monthlyPayment = Math.round((principalManwon * (monthlyRate * x)) / (x - 1)); const totalPayment = monthlyPayment * totalMonths; return { monthlyPayment, totalInterest: totalPayment - principalManwon, totalPayment }; }
